Removed necessity of a config file
TheThingsNetwork/packet_forwarder pull request #16
Opened 2017-05-10 09:38 UTC by dotpy3

Fixes the catch-22 situation of #13 where the program requires a configuration file to start, even to use the `configure` command.

2017-05-10 10:52 UTC, johanstokking requested changes
I think this is cleaner: https://github.com/TheThingsNetwork/ttn/blob/develop/cmd/root.go#L166-L179

2017-05-10 12:13 UTC, dotpy3 commented
If we do this, this means the packet forwarder refuses to start if there is no config file (because of the `os.Exit(1)`). This means that the `configure` command doesn't work unless there is already a configuration file => so it means we have to make every user aware that s.he should create an empty config file before starting the packet forwarder for the first time. I think it would be better instructing users to use `packet-forwarder configure` before starting the packet forwarder, rather than instructing them to create an empty config file.

2017-05-10 12:56 UTC, johanstokking commented
Afaik it doesn't exit when there's no config file, only if it fails. See the first part

2017-05-10 14:58 UTC, johanstokking commented
I think we should just rely on Viper here and whatever we use elsewhere. It doesn't crash when there's no file present, but it should crash when somebody explicitly passes a `config` flag with a file that can't be read.

2017-05-10 15:50 UTC, dotpy3 commented
It seems Viper crashes when there is no file present. I tried this:

```bash
$ git co develop
$ rm $HOME/.pktfwd.yml
$ make clean && make build
[...]
$ ./release/packet-forwarder-darwin-amd64-imst_rpi-mac configure
Error when reading config file: Config File ".pktfwd" Not Found in "[/Users/egourlao]"
```

Given that `viper.SetConfigFile(cfgFile)` (in `cmd/root.go`) is called whatever the command, it makes `viper.SetConfigFile(cfgFile)` return an error in every case, from the moment there is no config file initialised.

2017-05-10 15:54 UTC, johanstokking commented
OK so why would it be any different than this? https://github.com/TheThingsNetwork/ttn/blob/master/cmd/root.go#L158-L180

It all works like a charm when there's no `~/.ttn.yml`

2017-05-10 15:58 UTC, dotpy3 commented
TTN seems to crash on my side when starting a component without any `$HOME/.ttn.yml` file:

```bash
$ ttn broker
Error when reading config file: Config File ".ttn" Not Found in "[/Users/egourlao]"
```

2017-05-11 13:33 UTC, dotpy3 commented
With the latest commit, there is now no need for a config file for the program to start.

2017-05-11 14:52 UTC, johanstokking approved these changes

2017-05-11 14:52 UTC, merged